image: mcr.microsoft.com/dotnet/core/sdk:3.1
 
stages:
  - build
  - publish
  - run

build:
 stage: build
 script:
  - dotnet build

publish-linux:
  stage: publish
  script:
    - export PREV_VERSION=$(grep "<VersionPrefix>" soemxmltosqlite/SoemXmlToSQLite.csproj | sed -E "s/.*<VersionPrefix>(.*)<\/VersionPrefix>.*/\\1")
    - export VERSION=$CI_PIPELINE_ID.$CI_PIPELINE_IID
    - echo $VERSION
    - dotnet publish -r linux-x64 --self-contained true
  artifacts:
    paths:
     - /builds/ata.akcay/soemxmltosqlite/bin/


