image: mcr.microsoft.com/dotnet/core/sdk:3.1
 
stages:
  - build
  - publish
  

build:
 stage: build
 script:
  - dotnet build

publish-linux:
  stage: publish
  script:
    - export VERSION=$CI_PIPELINE_ID.$CI_PIPELINE_IID
    - echo $VERSION
    - dotnet publish -c Release -r linux-x64 --self-contained true
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_PIPELINE_IID-linux-x64"
    paths:
     - bin/Release/


